a little cleanup

diff --git a/ambetter_eob_fix_2025 b/ambetter_eob_fix_2025
--- a/ambetter_eob_fix_2025
+++ b/ambetter_eob_fix_2025
@@ -25,7 +25,6 @@ do1file() (
    extension="${filename##*.}"              # ; echo "extension $extension"
    basename="${filename%.*}"                # ; echo "basename  $basename"
    # logical parameters:
-   rotdnm="$dirname/origrot" ; test -d "$rotdnm" || mkdir -p "$rotdnm"  # where rotated version of original file is created
    outdnm="$dirname/reduced" ; test -d "$outdnm" || mkdir -p "$outdnm"  # where reduced+rotated version of original file is created
    bakdnm="$dirname/backup"  ; test -d "$bakdnm" || mkdir -p "$bakdnm"  # where original file is moved
 
@@ -41,14 +40,13 @@ do1file() (
    # correctly-rotated version of the original file (i.e. one removing no pages)
    # and run `rename_ambetter_eob` on it (successfully)!  Goofy but it works.
 
-   if something; then
-
-   # 20250110_1009 Fri rotation now unnecessary
-   # see "$qpdf" "$fullname" --rotate=+90:2-$lastpg -- "$rotdnm/$filename" || die "$qpdf [rotdnm] failed"
-   # see rename_ambetter_eob "$rotdnm/$filename"
-   # 20250110_1009 Fri rotation now unnecessary
-   # see "$qpdf" "$fullname" --pages . "$firstpg"-"$lastpg" -- --rotate=+90 "$outdnm/$filename" || die "$qpdf [outdnm] failed"
-
+   if false; then
+     # 20250110_1009 Fri rotation now unnecessary as late in 2024 Ambetter came to their senses
+     rotdnm="$dirname/origrot" ; test -d "$rotdnm" || mkdir -p "$rotdnm"  # where rotated version of original file is created
+     see "$qpdf" "$fullname" --rotate=+90:2-$lastpg -- "$rotdnm/$filename" || die "$qpdf [rotdnm] failed"
+     see rename_ambetter_eob "$rotdnm/$filename"
+     20250110_1009 Fri rotation now unnecessary
+     see "$qpdf" "$fullname" --pages . "$firstpg"-"$lastpg" -- --rotate=+90 "$outdnm/$filename" || die "$qpdf [outdnm] failed"
    fi
 
    see "$qpdf" "$fullname" --pages . "$firstpg"-"$lastpg" -- "$outdnm/$filename" || die "$qpdf [outdnm] failed"
