sample cron.d & hlthchk_ping scripts; minor improvements

diff --git a/smart_check_all b/smart_check_all
--- a/smart_check_all
+++ b/smart_check_all
@@ -1,25 +1,37 @@
 #!/usr/bin/env bash
 
+# intended use: predicate for cron script pinging healthchecks.io
+#
+# sample cron.d:
+#-----------------------------------------------------------------
+# # /etc/cron.d/smart_check_all: crontab fragment
+#
+# HC_UUID=my-uuid
+# # run every 10AM   0 10
+# 0 10 * * *  root  /root/smart_check_all ; /root/hlthchk_ping $?
+#-----------------------------------------------------------------
+# where /root/hlthchk_ping contains
+# #!/usr/bin/env bash
+#
+# HC_URL="https://hc-ping.com/"
+# # set -x
+# /usr/bin/curl -fsS -m 10 --retry 5 -o /dev/null "$HC_URL$HC_UUID${1:+/}$1"
+#-----------------------------------------------------------------
+
 die() { printf %s "${@+$@$'\n'}" 1>&2 ; exit 1 ; }
-see() ( { set -x; } 2>/dev/null ; "$@" ) ;
 
 # smartctl must be run as root to do anything useful
 (( EUID == 0 )) || die "smart_check_all: must run as root!"  # cannot log
+
 logf="${SMART_CHECK_ALL_LOGFILE:-"/root/smart_check_all.log"}"
-log() { printf "$(ts) %s\n" "$*" >> "$logf" ; }
-die() { log "$@" ; exit 1 ; }
+log() { echo "${@+"$(date +'%y%m%dt%H%M%S') $*"}" >> "$logf" ; }
+die() { echo "$@" 1>&2 ; log "$@" ; exit 1 ; }
 
-ts() { date +'%y%m%dt%H%M%S' ; }
-
-echo >> "$logf" ; log "starting"
-
-PATH="$PATH:/usr/sbin"  # smartctl lives here
-
+log ; log "starting"  # empty line precedes each run's log sequence
+PATH="$PATH:/usr/sbin"  # smartctl lives here, missing from root cron PATH
 command -v findmnt  > /dev/null || die "smart_check_all: findmnt command not available; PATH=$PATH"
 command -v smartctl > /dev/null || die "smart_check_all: smartctl command not available; PATH=$PATH"
-
-secs_start=$SECONDS
-failcount=0 devcount=0
+secs_start=$SECONDS failcount=0 devcount=0
 while read -r UUID SIZE SOURCE TARGET LABEL ; do
    (( ++devcount ))
    # echo "UUID=$UUID,SIZE=$SIZE,SOURCE=$SOURCE,TARGET=$TARGET,LABEL=$LABEL"
