++concision

diff --git a/tomp3normvol b/tomp3normvol
--- a/tomp3normvol
+++ b/tomp3normvol
@@ -13,16 +13,10 @@ outfnm_suffix="_normvol.mp3"
 
 normvol_to_mp3() (
    outfnm="${1%.*}$outfnm_suffix"
-   if [[ -f "$outfnm" && "$outfnm" -nt "$1" ]]; then
-      echo "exists $outfnm"
-   else
-      if ! dbadj="$(read_mean_volume_neg_db "$1")"; then
-         echo "read_mean_volume_neg_db failed on $1"
-      else
-         ffmpeg -i "$1" -y -f mp3 -q:a 0 -af "volume=${dbadj}dB" "$outfnm" 2> /dev/null || die "normvol failed on $1"
-         printf "+%3d dB %s\n" "$dbadj" "$outfnm"
-      fi
-   fi
+   [[ -f "$outfnm" && "$outfnm" -nt "$1" ]] && die "exists $outfnm"
+   dbadj="$(read_mean_volume_neg_db "$1")" || die "read_mean_volume_neg_db failed on $1"
+   printf "+%3ddB %s\n" "$dbadj" "$outfnm"
+   ffmpeg -i "$1" -y -f mp3 -q:a 0 -af "volume=${dbadj}dB" "$outfnm" 2> /dev/null || die "normvol failed on $1"
    )
 
 for fnm in "$@"; do
